### ISSUE TITLE
getting contact with shadow team  to see how they build server on ANU

### ISSUE THREAD

**Issue by JingLi201802** [JingLi201802/Taxonomic#4]
getting contact with shadow team  to see how they build server on ANU. If not applicable, research other server platforms (Herok)

**Comment by afuchs1** [comment]
Hi Jing

I checked this ticket but there is no mention of the outcome - how did you go?

cheers Anne

Sent from my iPad

On 15 Aug 2019, at 6:17 pm, JingLi201802 <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #4<https://github.com/JingLi201802/Taxonomic/issues/4>.
